config/routes.rb
BotherBox::Application.routes.draw do
  resources :posts
  root to: 'posts#index'
  post '/like/:id' => 'posts#like', as: :like
end

app/models/post.rb
class Post < ActiveRecord::Base
  validate :name, presence: true
  validate :description, presence: true
  before_create { self.timestamp = Time.now }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(timestamp: :desc)
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def like
   @post.update_attributes(likes: @post.likes + 1)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        @post.update_attributes(timestamp: Time.now)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :description, :likes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_timestamp(post)
    if post.timestamp.to_date == Date.today
      post.timestamp.strftime("%l:%M %P")
    else
      post.timestamp.strftime("%m:%D")
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BotherBox</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Bothered at UChicago</h1>

<div class="new_form">
  <h2 id="toggle_form">Make a new post</h2>
  <%= render 'form' %>
</div>

<table class="all-posts sortable-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Description</th>
      <th>Likes <i class="fa fa-sort"></i></th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr data-post-id=<%=post.id%>>
        <td>
          <%= post.name %><br/>
          <p class="post_updated_at">(<%=format_timestamp(post) %>)</p>
        </td>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td class="num_likes"><%= post.likes %></td>
        <td><%= link_to 'Edit', edit_post_path(post), class: "edit button" %> |
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete button"  %> |
          <%= link_to 'Like', like_path(post), method: :post, remote: true, class: "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/like.js.erb
$('tr[data-post-id=' + <%=@post.id%> + '] .num_likes').html(<%= @post.likes %>)

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @post.likes %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>